### PR TITLE
Update your README.md

### PR DESCRIPTION
**Pull request by luisRojas29**
Look for the number 5 instruction... it says that we need to make changes inside here and then click on the create pull request button...so here I am... regards...

### CODE REVIEW

**Comment by bruceLeeO** [comment]
oh i see.. okay... I'll check it out.. after looking over instruction #5, it seems there's been a new change to the wording from last night... anyways, I don't see any comments from you about my purpose section of the writing, the section about "What to Use TrumpScript for and When to Use It"  - does that mean I did a greater than great job?  ;)  If it is then that's great.  But I don't think I can merge your pull request because it contains your portion of the assignment - our subsequent pull request to the owner's would show my request containing your "For the non-technical, for America section of the readme.  Regards

**Comment by luisRojas29** [comment]
What do you mean not comments?? So how we doing??

**Comment by bruceLeeO** [comment]
you need to give me some feedback on my Part (b) assignment;  Any suggestion must be done in your local machine so when you create a pull request I can accept it or ignore it... if I accept it I can then merge it as a final "polished" product;  then and only then I can create a pull request to the owner of the TrumpScript repository so they can look over it and decide if they would also accept or ignore it.  Get it??? Let me know... Last night I provided you with the steps to do that Regards

**Comment by luisRojas29** [comment]
Ok I did what you said and when I try to git push origin returns me with this error:
`Permission to bruceLeeO/TrumpScript.git denied to luisRojas29.
fatal: unable to access 'https://github.com/bruceLeeO/TrumpScript.git/': The requested URL returned error: 403` So, do you have to make permission to me??

**Comment by bruceLeeO** [comment]
hmm, there shouldn't be any permission needed because when you clone bruceLeeO repository into you local machine that's your own copy of that repository.  you can make any changes and commit and then pull request so I can check the contribution changes you had made on that repository

**Comment by luisRojas29** [comment]
So it's not pushing, only make a pull request... let me try that...

**Comment by luisRojas29** [comment]
Mmm... still nothing, could you please merge this actually pull request, so we can see what it does??

**Comment by bruceLeeO** [comment]
sure thing

**Comment by luisRojas29** [comment]
I can see my part (a) in your fork repo inside the branch purpose-readme-contribution in fact this branch has everything part (a) and (b), and the non-developer-readme-contribution only has my part (a)

**Comment by luisRojas29** [comment]
Do you think this is it?? If so, will you please go to my fork project page, inside the non-developer-readme-contribution README.md post your changes and then make a pull request??

**Comment by bruceLeeO** [comment]
sorry for the constant delay Luis... juggling between making dinner for my kids and getting them ready for bed.... having both part (a) and part (b) is fine i guess... but only one of us  can make the pull request because the owners might get confused why two different pull request is created for the same changes.  I think the assignment is calling for both collaborators to experience being a contributor and the owner.  And the final stage of the assignment is for each collaborator to create pull requeston their part of the assignment.   let me know what you want to do... regards

**Comment by luisRojas29** [comment]
Don't worry... I have no rush... Ok, so because your fork has the two parts of the assignment, I suggest you make the pull request to the owner, the part that you make change on my fork repo is for having a backup in case the Modern Developer people ask for my assignment... If you think we're ready to go... lets improve TrumpScript...jejeje... regards

**Comment by bruceLeeO** [comment]
alrighty... I'm working on it right now... i'll let you know... regards

**Comment by bruceLeeO** [comment]
you know what... I think it was already done 23 hours ago... here the link of the pull request https://github.com/samshadwell/TrumpScript/pull/110

**Comment by luisRojas29** [comment]
Jajaja nice... hope that the chat in Q&A will be soon... so we can communicate a little more fluid... but this was great... thank you, hope we can work together in another project. Best regards... see you on MD...

**Comment by bruceLeeO** [comment]
lol too... same here Luis... Richard responded to one of my comment saying that chat should be up this week  best regard as well

**Pull request merged**
