### PR TITLE
Making a great explanation and motivation for the non-technical

### PR DESCRIPTION
**Pull request by luisRojas29**
Hey, I've created and introduction for the non-technical people, like try to make it clear and very easy to invite to play and program with TrumpScript.

### CODE REVIEW

**Comment by bruceLeeO** [comment]
Thanks Luis, I just realized I can make a comment here... lol... anyways let me know as soon as you are done checking my portion of the assignment

**Comment by luisRojas29** [comment]
Ok, let me check it...

**Comment by luisRojas29** [comment]
Very nice... I already corrected my typos, so I think we ready to go... what's next??

**Comment by bruceLeeO** [comment]
Alright! this is so cool... I guest the next step would be to merge and then proceed to step 6

**Comment by luisRojas29** [comment]
Do we have to do this the two of us??

**Comment by bruceLeeO** [comment]
Hey Luis.  I will get back with in an hour.  I'm still at work

**Comment by luisRojas29** [comment]
Ok, don't worry...

**Comment by bruceLeeO** [comment]
HEY Luis, I think the answer to your question above is YES.  on step 5 we are suppose to fork each others repository, edit the readme  and commit the correction. Then we create a pull request and then  "collaborate" -- which i think we already did. The next step is to merge the pull request and then we are to create a pull request to the owners;

I guess if I am reading these instructions right the purpose of forking is to edit each others readme file.  then when we finish editing and commit we create a pull request so we both can review each others edited file.  Once we are satisfied with the changes we then merge the files   

After that, back to our forked repository we create a new pull request to the owners of the repository.  So Luis you will be creating a pull request for Part (a) of the assignment to the owners and I will be creating a pull request for Part (b) of the assignment to the owners.

I hope all these makes sense

**Comment by luisRojas29** [comment]
Ok... I think already pull request to your fork repo... so you just include my changes, and vice-versa, I'm waiting for you to pull request my fork repo...

**Pull request closed without merging**
